//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package pt.carlos.alex.rosario;

import android.os.Bundle;
import android.os.Handler;
import android.support.v4.view.ViewPager;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import pt.carlos.alex.rosario.R.layout;

public final class MostraOracoes_
    extends MostraOracoes
{

    private View contentView_;
    private Handler handler_ = new Handler();

    private void init_() {
        beforeCreate();
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_();
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        mPager = ((ViewPager) findViewById(pt.carlos.alex.rosario.R.id.pager));
        mIndicator = ((ContasRosario) findViewById(pt.carlos.alex.rosario.R.id.indicator));
        afterCreate();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.oracoes_page_layout, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public void geraPageView() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    MostraOracoes_.super.geraPageView();
                } catch (RuntimeException e) {
                    Log.e("MostraOracoes_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void initDezena() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    MostraOracoes_.super.initDezena();
                } catch (RuntimeException e) {
                    Log.e("MostraOracoes_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
